{% set name = "kafkit" %}
{% set version = "0.3.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kafkit-{{ version }}.tar.gz
  sha256: b16dc5f3c698afdc5771636f13f8a418d48be931519fdc395a738926ea3d8254

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >={{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - fastavro
    - uritemplate

test:
  imports:
    - kafkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://kafkit.lsst.io
  summary: Kafkit helps you write Kafka producers and consumers in Python with asyncio.
  dev_url: https://github.com/lsst-sqre/kafkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonathansick
